services:
  # Order App Services
  order-backend:
    build: 
      context: order-app/back
      dockerfile: Dockerfile
    container_name: order-backend
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8081
      - PAYMENT_SERVICE_BASE_URL=http://payment-backend:8082
    networks:
      - app-network
    depends_on:
      - payment-backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  order-frontend:
    build:
      context: order-app/front
      dockerfile: Dockerfile
    container_name: order-ui
    ports:
      - "5173:80"
    depends_on:
      - order-backend
    environment:
      - VITE_API_URL=http://order-backend:8081
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Payment App Services
  payment-backend:
    build: 
      context: ./payment-app/back
      dockerfile: Dockerfile
    container_name: payment-backend
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8082
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  payment-frontend:
    build:
      context: ./payment-app/front
      dockerfile: Dockerfile
    container_name: payment-ui
    ports:
      - "5174:80"
    depends_on:
      - payment-backend
    environment:
      - VITE_API_URL=http://payment-backend:8082
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Incident App Services
  incident-backend:
    build: 
      context: ./incident-app/back
      dockerfile: Dockerfile
    container_name: incident-backend
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8083
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/api/incidents/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  incident-frontend:
    build:
      context: ./incident-app/front
      dockerfile: Dockerfile
    container_name: incident-ui
    ports:
      - "5175:80"
    depends_on:
      - incident-backend
    environment:
      - VITE_API_URL=http://incident-backend:8083
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Shared Database
  mongo:
    image: 'mongo:7.0.5'
    container_name: mcp-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
    