services:
  backend:
    build: 
      context: ./back
      dockerfile: Dockerfile
    container_name: payment-backend
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8082
    networks:
      - payment-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: payment-ui
    ports:
      - "5174:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8082
    networks:
      - payment-network
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  payment-network:
    driver: bridge
