services:
  backend:
    build: 
      context: ./back
      dockerfile: Dockerfile
    container_name: order-backend
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8081
    networks:
      - order-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: order-ui
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8081
    networks:
      - order-network
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  order-network:
    driver: bridge
